# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'E Store' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for E Store
  pod 'Moya/RxSwift', '~> 15.0'

  target 'E StoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'E StoreUITests' do
    # Pods for testing
  end

end
